config/routes.rb
Fashion2day::Application.routes.draw do
	match '/login', 	:to => 'sessions#login'
	match '/logout', 	:to => 'sessions#destroy'
  match '/welcome', :to => 'sessions#welcome'
  match '/lookup',  :to => 'addresses#lookup'
  root 							:to => 'pages#home'
  resources :users
  resources :sessions, :only => [:login, :create, :destroy, :welcome]
  resources :categories
	resources :subcategories
  resources :addresses











end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	include ApplicationHelper
	before_filter :admin_user

  # GET /subcategories
  # GET /subcategories.json
  def index
    #@subcategories = Subcategory.find_by_category_id(params[:id])
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  def show
		@category = Category.find(params[:id])
    @subcategories = Subcategory.find_all_by_category_id(params[:id])
  end

  # GET /subcategories/new
  def new
    category = Category.find(params[:id])
    @subcategory = Subcategory.new
    @subcategory.category_id = category.id
  end

  # GET /subcategories/1/edit
  def edit
		@subcategory = Subcategory.find(params[:id])
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(params[:subcategory])

      if @subcategory.save
				flash[:success] = "Subkategorie wurde gespeichert."
        redirect_to subcategory_path(@subcategory.category_id)
      else
        render "new"
      end
  end

  # PUT /subcategories/1
  def update
    @subcategory = Subcategory.find(params[:id])

    if @subcategory.update_attributes(params[:subcategory])
			flash[:success] = "Subkategorie wurde geaendert."
	    redirect_to @category
    else
    	render :action => "edit"
    end
  end

  # DELETE /subcategories/1
  def destroy
    @subcategory = Subcategory.find(params[:id])
     if @subcategory.destroy
		 		flash[:success] = "Subkategorie wurde geloescht."
    		redirect_to subcategory_path(@subcategory.category_id)
     else
     		flash[:error] = "Subkategorie kann nicht entfernt werden (wird noch verwendet)."
     		redirect_to  subcategory_path(@subcategory.category_id)
     end
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <p>Speicherung der Unterkategorie wurde verhindert: <%= pluralize(@subcategory.errors.count, "Fehler") %></p>

      <ul>
      <% @subcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="login">
    <table>
    	<tr>
	      <td><%= f.label :category_id, "Kategorie" %></td>
	      <td><%= f.select :category_id,
	        Category.find(:all).collect{|d| [d.name, d.id]},
	        :prompt => "Bitte waehlen" %></td>
	    </tr>

    	<tr>
	      <td><%= f.label :name %></td>
	      <td><%= f.text_field :name %></td>
	    </tr>
  	</table>
  </div>
  	<div class="actions">
    	<%= f.submit "speichern" %></td>
  	</div>
<% end %>

app/views/subcategories/edit.html.erb
<h3>Unterkategorie bearbeiten</h3>
<%= render 'form' %>
<%= link_to 'Back', categories_path %>

app/views/subcategories/index.html.erb
<h3>Unterkategorie</h3>
<p class="cmd-line">
	<%= link_to 'Kategorie-Uebersicht', categories_path %> | 
  <%= link_to 'zurueck', categories_path %>
</p>

<div id="list">
	<table>
	  <tr>
	    <th>Name</th>
	  </tr>

		<% @subcategories.each do |subcategory| %>
	  	<tr>
	    	<td><%= link_to subcategory.name, edit_subcategory_path(subcategory) %></td>
	  	</tr>
		<% end %>
	</table>
</div>

app/views/subcategories/new.html.erb
<h3>Neue Unterkategorie</h3>
<p class="cmd-line"><%= link_to 'zurueck', categories_path %></p>
<%= render 'form' %>

app/views/subcategories/show.html.erb
<h3>Kategorie-Subkategorie</h3>
<p class="cmd-line">
   <%= link_to 'Neue Zuordnung', new_subcategory_path(:id => @category.id) %> |
	 <%= link_to 'zurueck', categories_path %>
</p>
<div id="list">
	<table>
     <thead>
     	<th><b><%= @category.name %></b></th>
			<th></th>
     </thead>
     <% @subcategories.each do |subcategory| %>
	      <tr>
	          <td><%= subcategory.name %></td>
						<td><%= link_to "entfernen", subcategory, :method => :delete, :confirm => "Zuordnung entfernen?" %></td>
	      </tr>
	   <% end %>
	</table>
</div>