config/routes.rb
Fashion2day::Application.routes.draw do
	match '/login', 	:to => 'sessions#login'
	match '/logout', 	:to => 'sessions#destroy'
  match '/welcome', :to => 'sessions#welcome'
  match '/lookup',  :to => 'addresses#lookup'
  root 							:to => 'pages#home'
  resources :users
  resources :sessions, :only => [:login, :create, :destroy, :welcome]
  resources :categories
	resources :subcategories
  resources :addresses











end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation,
  								:last_visit, :aktiv

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	# VALIDATIONS START =========================================

  validates :name, 	:presence => true,
  					:length => { :maximum => 50 }

	validates :email, :presence => true,
  					:format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false },
            :on => :create

	validates :email, :presence => true,
  					:format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false },
            :on => :update

  validates	:password, :confirmation => true,
  					:presence => true,
            :length => { :within => 6..25 },
            :on => :create

	validates	:password, :confirmation => true,
  					:presence => true,
            :length => { :within => 6..25 },
            :on => :update,
				    :unless => :skip_validation_on_update

	# VALIDATIONS END ===========================================

  before_save :encrypt_password

  def has_password?(submitted_password)
		encrypted_password = encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
  	user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

  def encrypt_password
  	self.salt = make_salt if new_record?
  	self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
		secure_hash("#{salt}--#{string}")
  end

  def make_salt
     secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
  	Digest::SHA2.hexdigest(string)
  end

  # nur wenn beim UPDATE ein neues Passwort vergeben wird,
  # soll die on=> :update - Validierung durchgeführt werden
  def skip_validation_on_update
  	if self.password.blank?
      return true
    end
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include ApplicationHelper
	before_filter :admin_user

  def index
		@title = "Anwender-Liste"
    @users = User.find(:all, :order => 'name')
  end

  def new
  	@title = "Neuer Anwender"
    @user = User.new
  end

  def create
     @user = User.create(params[:user])
     if @user.save
     	flash[:success] ="Anwender wurde gespeichert!"
      redirect_to(users_path)
     else
     	render 'new'
     end
  end

  def edit
  	@title = "Anwender bearbeiten"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
    	flash[:success] ="Anwenderdaten wurden geaendert!"
      redirect_to(users_path)
    else
    	@title = "Anwender bearbeiten"
      render 'edit'
    end
  end


  def destroy
    user = User.find(params[:id])
    	if not_current_user(user)
	    	User.find(user).destroy
    		flash[:success] ="Anwenderdaten wurden geloescht!"
    		redirect_to users_path
      else
        flash[:error] ="Dieser Vorgang ist nicht erlaubt!"
				redirect_to users_path
      end
  end

  private

  def not_current_user(user)
      current_user != user ? true : false
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<p class="cmd-line"><%= link_to "zurueck", users_path %></p>
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
    <div id="error_explanation">
    <p>Speicherung des Anwenders wurde verhindert: <%= pluralize(@user.errors.count, "Fehler") %> </p>
    <ul>
       <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
       <% end %>
    </ul>
	<% end %>
  <div id ="login">
    <table>
      <tr>
      	<td><%= f.label :name %></td>
	    	<td><%= f.text_field :name %><td>
    	</tr>
      <tr>
      	<td><%= f.label :email %></td>
	    	<td><%= f.text_field :email %></td>
    	</tr>
	  	<tr>
	    	<td><%= f.label :password, "Kennwort" %></td>
	    	<td><%= f.password_field :password %></td>
	  	</tr>
	  	<tr>
	    	<td><%= f.label :password_confirmation, "Kennwort wiederholen" %></td>
	    	<td><%= f.password_field :password_confirmation %></td>
	  	</tr>
	  	<tr>
	    	<td><%= f.label :Aktiv, "Ist Anwender aktiv?" %></td>
	    	<td><%= f.check_box :aktiv %></td>
	  	</tr>
  	</table>
  </div>
  <div>
   	<table>
   		<tr>
				<td><%= f.submit "speichern" %></td>
			</tr>
  	</table>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Anwenderdaten bearbeiten</h3>
<%= render :partial  => "form" %>

app/views/users/index.html.erb
<h3>Anwender-Liste</h3>
<p class="cmd-line">
	<%= link_to "neuer Anwender", new_user_path %> | <%= link_to "zurueck", welcome_path %>
</p>
<div id="list">
  <table>
    	<thead>
    		<tr>
      		<th>Name</th>
      		<th>Email</th>
					<th></th>
					</tr>
      </thead>
    <% for user in @users %>
      <tr>
        <td><%= link_to user.name, edit_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= link_to "loeschen", user, :method => :delete,
        				:confirm => "Sind Sie sicher?",
								:title => "Delete #{user.name}" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h3>Neuer Anwender</h3>
<%= render :partial  => "form" %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>