config/routes.rb
Fashion2day::Application.routes.draw do
	match '/login', 	:to => 'sessions#login'
	match '/logout', 	:to => 'sessions#destroy'
  match '/welcome', :to => 'sessions#welcome'
  match '/lookup',  :to => 'addresses#lookup'
  root 							:to => 'pages#home'
  resources :users
  resources :sessions, :only => [:login, :create, :destroy, :welcome]
  resources :categories
	resources :subcategories
  resources :addresses











end

app/helpers/addresses_helper.rb
module AddressesHelper
	include ApplicationHelper
end

app/views/addresses/Kopie von index.html.erb
<h3>Adressen</h3>
<p class="cmd-line">
   <%= link_to 'Neue Adresse', new_address_path %> |
	 <%= link_to 'zurueck', welcome_path %>
</p>
<div id="adrsuche">
	<table>
	  <tr>
	      <td><%= label :suche, 'Suchen' %></td>
	  </tr>
	  <% form_tag :action => "lookup" do %>
	    <tr>
	      <td><%= select_tag "suchfeld",
	              options_from_collection_for_select(@lookups, "id", "anzeige"),
	              :prompt => "Bitte waehlen" %></td>
	      <td><%= text_field_tag :suchwert %></td>
	      <td><%= submit_tag "los" %></td>
	    </tr>
	  <% end %>
	</table>
</div>
<div id="list">
	<table>
	   <% @addresses.each do |address| %>
	      <tr>
	          <td><%= link_to address.firma, edit_address_path(address) %></td>
						<td><%= address.nachname %></td>
	      </tr>
	   <% end %>
	</table>
</div>

app/views/addresses/NEU _form.html.erb
<%= form_for(@address) do |f| %>
	<% if @address.errors.any? %>
  	<div id="error_explanation">
  		<p>Speicherung der Adresse wurde verhindert: <%= @address.errors.count %> Fehler </p>
			<ul>
  			<% @address.errors.full_messages.each do |msg| %>
    			<li><%= msg %></li>
  			<% end %>
			</ul>
  	</div>
  <% end %>
	<div id="adresse">
    <% if !@address.new_record? %>
    	<p>update am <%= german_time(@address.updated_at) %> durch <%= @address.user %></p>
    <% end %>
    <table>
			<tr>
	      <td><%= f.label :firma %></td>
	      <td><%= f.text_field :firma %></td>
        <td><%= f.label :category, "Kategorie" %></td>
	  		<td><%= f.select :category_id,
	  				Category.find(:all, :order => :name).collect{|d| [d.name, d.id]},
	  				:prompt => "Bitte waehlen" %></td>
      </tr>
      <tr>
				<td><%= f.label :nachname, "Name" %></td>
		    <td><%= f.text_field :nachname %></td>
        <td><%= f.label :subcategory, "Sub-Kat." %></td>
	    	<td><%= f.select :subcategory_id,
	          		Subcategory.find(:all, :order => :name).collect{|d| [d.name, d.id]},
	          	:prompt => "Bitte waehlen" %></td>
			</tr>
      <tr>
      	<td><%= f.label :vorname %></td>
	    	<td><%= f.text_field :vorname %></td>
        <td><%= f.label :fon, 'Telefon' %></td>
		    <td><%= f.text_field :fon %></td>
      </tr>
      <tr>
      	<td><%= f.label :position %></td>
			  <td><%= f.text_field :position %></td>
        <td><%= f.label :fax %></td>
	   	 	<td><%= f.text_field :fax %></td>
      </tr>
      <tr>
      	<td><%= f.label :strasse %></td>
	    	<td><%= f.text_field :strasse %></td>
      	<td><%= f.label :email %></td>
	    	<td><%= f.text_field :email %></td>
      </tr>
      <tr>
      	<td><%= f.label :hausnr, "Haus-Nr." %></td>
		    <td><%= f.text_field :hausnr %></td>
        <td><%= f.label :web %></td>
			  <td><%= f.text_field :web %></td>
      </tr>
      <tr>
      	<td><%= f.label :plz %></td>
	  		<td><%= f.text_field :plz %></td>
        <td><%= f.label :briefkontakt, "Brief" %></td>
		    <td><%= f.select :briefkontakt,
	    					Lettercontact.find(:all, :order => :description).collect{|d| [d.description]},
	  						:prompt => "Bitte waehlen" %></td>
      </tr>
      <tr>
      	<td><%= f.label :ort %></td>
	  		<td><%= f.text_field :ort %></td>
      </tr>
      <tr>
        <td><%= f.label :land, "Land" %></td>
	  		<td><%= f.select :land,
	  			Country.find(:all, :order => :de).collect{|d| [d.de]},
	  			:prompt => "Bitte waehlen" %></td>
      </tr>
    </table>
  	<div class="go">
  		<%= f.submit "speichern" %>
  	</div>
	</div>
<% end %>

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
	<% if @address.errors.any? %>
  	<div id="error_explanation">
  		<p>Speicherung der Adresse wurde verhindert: <%= @address.errors.count %> Fehler </p>
			<ul>
  			<% @address.errors.full_messages.each do |msg| %>
    			<li><%= msg %></li>
  			<% end %>
			</ul>
  	</div>
  <% end %>
	<div id="adresse">
    <% if !@address.new_record? %>
    	<p>update am <%= german_time(@address.updated_at) %> durch <%= @address.user %></p>
    <% end %>
    <div class="left">
      <table>
      	<tr>
      		<td><%= f.label :firma %></td>
	    		<td><%= f.text_field :firma %></td>
      	</tr>
      	<tr>
      		<td><%= f.label :nachname, "Name" %></td>
	    		<td><%= f.text_field :nachname %></td>
      	</tr>
      	<tr>
      		<td><%= f.label :vorname %></td>
	    		<td><%= f.text_field :vorname %></td>
      	</tr>
      	<tr>
        	<td><%= f.label :position %></td>
	    		<td><%= f.text_field :position %></td>
      	</tr>
        <tr>
        	<td><%= f.label :strasse %></td>
      		<td><%= f.text_field :strasse %></td>
        </tr>
        <tr>
         	<td><%= f.label :hausnr, "Haus-Nr." %></td>
    			<td class="small"><%= f.text_field :hausnr %></td>
        </tr>
        <tr>
          <td><%= f.label :plz %></td>
	  			<td class="small"><%= f.text_field :plz %></td>
    			</div>
        </tr>
        <tr>
    			<td><%= f.label :ort %></td>
	  			<td><%= f.text_field :ort %></td>
        </tr>
        <tr>
          <td><%= f.label :land, "Land" %></td>
	  			<td><%= f.select :land,
	  					Country.find(:all, :order => :de).collect{|d| [d.de]},
	  					:prompt => "Bitte waehlen" %></td>
      	</tr>
      </table>
    </div>
  	<div class="right">
    	<table>
				<tr>
  				<td><%= f.label :category, "Kategorie" %></td>
      	  <td><%= f.select :category_id,
		      		Category.find(:all, :order => :name).collect{|d| [d.name, d.id]},
	            :prompt => "Bitte waehlen" %></td>
        </tr>
        <tr>
          <td><%= f.label :subcategory, "Sub-Kat." %></td>
	        <td><%= f.select :subcategory_id,
	              	Subcategory.find(:all, :order => :name).collect{|d| [d.name, d.id]},
	              	:prompt => "Bitte waehlen" %></td>
         <tr>
          	<td><%= f.label :fon, 'Telefon' %></td>
	        	<td><%= f.text_field :fon %></td>
         </tr>
         <tr>
          	<td><%= f.label :fax %></td>
	        	<td><%= f.text_field :fax %></td>
         </tr>
         <tr>
          	<td><%= f.label :email %></td>
	        	<td><%= f.text_field :email %></td>
         </tr>
         <tr>
          	<td><%= f.label :web %></td>
	        	<td><%= f.text_field :web %></td>
         </tr>
         <tr>
          	<td><%= f.label :briefkontakt, "Brief" %></td>
	        	<td><%= f.select :briefkontakt,
	              Lettercontact.find(:all, :order => :description).collect{|d| [d.description]},
	        			:prompt => "Bitte waehlen" %></td>
      	 </tr>
      </table>
    </div>
  	<div class="go">
  		<%= f.submit "speichern" %>
  	</div>
	</div>
<% end %>

app/views/addresses/edit.html.erb
<h3>Adresse bearbeiten</h3>
<p class="cmd-line"><%= link_to 'zurueck', addresses_path %></p>
<%= render 'form' %>

app/views/addresses/index.html.erb
<h3>Adressen</h3>
<p class="cmd-line">
   <%= link_to 'Neue Adresse', new_address_path %>
    &nbsp;|&nbsp;<%= link_to 'zurueck', welcome_path %>
</p>
<div>
  <span class="export">
	<% form_tag addresses_path, :method => 'get' do %>
  	<%= label_tag :suche, 'Suchen' %>
    <%= select_tag :spalte,
	  			options_from_collection_for_select(@lookups, "id", "anzeige", @curselected),
	      	:prompt => "Bitte waehlen" %>
    <%= text_field_tag :search, params[:search], :size => 20 %>
    <%= label_tag :suche, 'sortieren nach' %>
    <%= select_tag :sort,
	  			options_from_collection_for_select(@sorts, "intern", "anzeige", @cursort),
	      	:prompt => "Bitte waehlen" %>
	  <%= submit_tag "los", :name => nil %>
		<% end %>
    <% form_tag addresses_path (:format => :csv), :method => 'get' do %>
			<%= text_field_tag :spalte, params[:spalte], :type => :hidden %>
			<%= text_field_tag :search, params[:search], :type => :hidden %>
			<%= text_field_tag :sort, params[:sort], :type => :hidden %>
			<span class="excel">
  			<%= submit_tag "Excel", :name => nil %>
			</span>
  	<% end %>
  </span
</div>
<div id="adrlist">
	<table>
		<% @addresses.each do |address| %>
  	  <tr>
	      <td><%= link_to address.firma, edit_address_path(address) %></td>
	      <td class="sidebar">
	      <strong><%= address.vorname %>&nbsp;<%= address.nachname %>&nbsp;&nbsp;
        	<span class="loesch" %><%= link_to 'entfernen', address,
        			:method => 'delete', :confirm => "Adresse entfernen?" , :title => "Adresse loeschen" %></span></strong><br />
	      <%= address.subcategory.name %><br />
	      <%= mail_to address.email, address.email, :title => "Email senden" %><br />
	      </td>
	    </tr>
		<% end %>
	</table>
</div>
<div class="digg_pagination">
<%= will_paginate %>
</div>

app/views/addresses/new.html.erb
<h3>Neue Adresse</h3>
<p class="cmd-line"><%= link_to 'zurueck', addresses_path %></p>
<%= render 'form' %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>