config/routes.rb
Fashion2day::Application.routes.draw do
	match '/login', 	:to => 'sessions#login'
	match '/logout', 	:to => 'sessions#destroy'
  match '/welcome', :to => 'sessions#welcome'
  match '/lookup',  :to => 'addresses#lookup'
  root 							:to => 'pages#home'
  resources :users
  resources :sessions, :only => [:login, :create, :destroy, :welcome]
  resources :categories
	resources :subcategories
  resources :addresses











end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
  has_many :addresses
  validates :name, :presence => true,
  								 :uniqueness => true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  include ApplicationHelper
	before_filter :admin_user

  # GET /categories
  def index
    @categories = Category.find(:all, :order => 'name').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  def create
    @category = Category.new(params[:category])
      if @category.save
        flash[:succes] = "Kategorie wurde angelegt."
        redirect_to categories_path
      else
        render "new"
      end
  end

  # PUT /categories/1
  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
        flash[:success] = "Kategorie wurde geandert."
        redirect_to categories_path
    else
        render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
			 flash[:success] = "Kategorie wurde geloescht!"
			redirect_to categories_url
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
  <div id ="login">
  	<table>
    	<tr>
  	  	<td><%= f.text_field :name %></td>
  		</tr>
  	</table>
  </div>
  <div class="actions">
		<%= f.submit 'speichern' %>
	</div>
<% end %>

app/views/categories/edit.html.erb
<h3>Kategorie bearbeiten</h3>
<p class="cmd-line">
	 <%= link_to 'Neue Zuordnung', new_subcategory_path(:id => @category.id) %>
   &nbsp;|&nbsp;<%= link_to 'zurueck', categories_path %></p>
<%= render 'form' %>

app/views/categories/index.html.erb
<h3>Kategorie-Liste</h3>
<p class="cmd-line">
   <%= link_to 'Neue Kategorie', new_category_path %>
	 &nbsp;|&nbsp;<%= link_to 'zurueck', welcome_path %>
</p>
<div id="list">
	<table>
	   <% @categories.each do |category| %>
	      <tr>
	          <td><b><%= link_to category.name, edit_category_path(category) %></b></td>
		        <td><%= link_to 'Zuordnungen', subcategory_path(category) %></td>
        </tr>
	   <% end %>
	</table>
</div>
<div class="digg_pagination">
	<%= will_paginate  %>
</div>

app/views/categories/new.html.erb
<h3>Neue Kategorie</h3>
<p class="cmd-line"><%= link_to 'zurueck', categories_path %></p>
<%= render 'form' %>
<br />